### ISSUE TITLE
Implement "Export to QuickBooks" button for simple React App

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/qb-export#1]
### We've selected a provider. Please don't respond to this bounty on GitCoin.
__________________

Please read the [README](https://github.com/TrueBlocks/qb-export) for description of the issue.

Use this issue to ask questions, report progress, etc.

| Type | Amount | Description |
|------|---------|-------------|
| Primary Bounty| 1,250 DAI | Implement "Export to QuickBooks" button |

These bonuses are available only after the primary bounty is completed and we approve the further work:

| Type | Amount | Description |
|------|---------|-------------|
| Bonus | 250 DAI | Implement import formats for other tools such as Rotki and Token Tax |
| Bonus | 250 DAI | Implement export to CSV and Tab Delimited Text |

**Comment by ManyRios** [comment]
We can work with a package to generate the file to download it or direct export... For the direct export to quickbooks we can talk in how proceed in a better way, But that can come after the functionality of the button

**Comment by tjayrush** [comment]
Sure. We can talk about anything. Please expand on what you're asking...

Concerning using a package, I presume you mean a package to do the export itself. I purposefully made the example repo very minimal because it is only a 'standin' for our app. I don't want to do any work related to the 'site' -- only the functionality of responding to the button push -- in other words -- only the export of the mocked data.

**Comment by murano1205** [comment]
Hi @tjayrush 
So for the primary bounty, you only want to expert data.js transactions into Quickbooks. 
Could you give me write access to this repo?

**Comment by ManyRios** [comment]
Account
0x000000000000

Asset
Eth | 0x000

Gas used
21000

Block hash
0x000000000000

Date                Amount in      Amount out.        Balance 

2017-02-15.         5.                                                   5



Format could be something like this, sorry for the rudimentary. I made it from my phone

**Comment by tjayrush** [comment]
The format is defined by QuickBlocks -- it's call IIF.

**Comment by johnmgrimm** [comment]
Hi, In case you will have problems with the feature delivery I will be happy to help. It seems to be a pretty straightforward task to implement. The Quickbooks provides a sandbox environment, so I can implement direct upload through the API and test the results there.

**Comment by tjayrush** [comment]
Thanks so much for your interest. We've already selected someone. I'll modify the above issue to make that more clear.

**Comment by naps62** [comment]
Some initial invevstigation work:
I manually built an ofx file (shown below) to import to Xero, which we're now using as a test environment alternative to Quickbook, for which OFX wasn't being accepted properly.

Due to some unfamiliarity with Xero, I could use some feedback on where to insert some of the desired attributes.
Once we validate that the import is working as intended, generating this file from the provided UI should be trivial


The file:
```ofx
OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:UTF-8
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:NONE

<OFX>
	<BANKMSGSRSV1>
		<STMTTRNRS>
			<TRNUID>2
			<STATUS>
				<CODE>0
				<SEVERITY>INFO
			</STATUS>
			<STMTRS>
				<CURDEF>USD
				<BANKACCTFROM>
					<BANKID>account-id
					<ACCTID>00001
					<ACCTTYPE>crypto
				</BANKACCTFROM>
				<BANKTRANLIST>
					<STMTTRN>
						<FITID>tx-id1
						<TRNTYPE>DEBIT
						<TRNAMT>-35.34
						<MEMO>assetAddr-here
						<DTPOSTED>20210806080000
						<REFNUM>tx-id1
						<CHECKNUM>tx-id2
					</STMTTRN>
					<STMTTRN>
						<FITID>tx-id2
						<TRNTYPE>DEBIT
						<TRNAMT>-35.34
						<MEMO>assetAddr2-here
						<DTPOSTED>20210806080000
						<SIC>tx-id2
					</STMTTRN>
				</BANKTRANLIST>
			</STMTRS>
		</STMTTRNRS>
	</BANKMSGSRSV1>
</OFX>
```

**Comment by tjayrush** [comment]
Reference for the data structure Reconciliation:

https://github.com/TrueBlocks/trueblocks-docs/issues/59

**Comment by tjayrush** [comment]
Excellent work. Thanks.
